Cancelling of duplicate tasks due to entity persistence
OpenSRP/opensrp-client-core pull request #741
Opened 2021-02-08 05:25 UTC by Rkareko

Resolves #734

2021-02-08 06:55 UTC, githengi commented on opensrp-app/src/main/java/org/smartregister/repository/EventClientRepository.java
> +                + " IN (" + StringUtils.repeat(",", taskIds.size()) + ")", taskIds.toArray(new String[0]));
```suggestion
                + " IN (" + StringUtils.repeat("?",",", taskIds.size()) + ")", taskIds.toArray(new String[0]));
```

2021-02-08 06:55 UTC, githengi commented on opensrp-app/src/main/java/org/smartregister/repository/TaskRepository.java
> +                "    COUNT(*) > 1";
can we remove the \n, maybe we use String.format?

2021-02-08 06:56 UTC, githengi commented on opensrp-app/src/main/java/org/smartregister/repository/TaskRepository.java
> +                "ORDER BY t1.for";
can we remove \n for readability of the query, you can use space at the end/start of each line

2021-02-10 20:02 UTC, githengi requested changes

2021-02-10 20:02 UTC, githengi commented on opensrp-app/src/main/java/org/smartregister/sync/helper/TaskServiceProcessor.java
> +            return;
if the local task if ready maybe the population should be skipped, however the task still needs to be deleted

2021-02-11 08:21 UTC, Rkareko commented on opensrp-app/src/main/java/org/smartregister/repository/TaskRepository.java
> +                "    _id, plan_id, for, code, COUNT(*) as count " +
removed

2021-02-15 14:06 UTC, githengi approved these changes

2021-02-16 04:47 UTC, merged