Add support for loading auth clients from local.properties
OpenSRP/opensrp-client-core pull request #767
Opened 2021-03-22 12:36 UTC by faidvd

Resolves #636

2021-04-06 13:22 UTC, ekigamba requested changes

2021-04-06 13:22 UTC, ekigamba commented on opensrp-app/src/main/java/org/smartregister/domain/Environment.java
> +    @SerializedName("id")
`client.id` would be better

2021-04-06 13:22 UTC, ekigamba commented on opensrp-app/src/main/java/org/smartregister/domain/Environment.java
> +    @SerializedName("secret")
`client.secret` would be better

2021-04-07 08:26 UTC, ekigamba commented
Looks good to me

2021-04-08 12:56 UTC, Rkareko commented
@faidvd please bump the version

2021-04-08 12:57 UTC, Rkareko commented
@faidvd can we have some javadocs for the public methods

2021-04-08 12:59 UTC, ndegwamartin reviewed
Can we add some java docs for the new classes and methods?

2021-04-08 13:40 UTC, ndegwamartin commented on opensrp-app/src/main/java/org/smartregister/view/activity/SettingsActivity.java
> +        if (newValue != null && UrlUtil.isValidUrl(newValue) && UrlUtil.isValidEnvironment(newValue)) {
Should the order here be changed?

2021-04-15 10:13 UTC, Rkareko commented on gradle.properties
> +VERSION_NAME=4.2.19-SNAPSHOT
Let's bump this up to `4.3.0` since it's new backward compatible feature

2021-04-15 10:46 UTC, Rkareko approved these changes

2021-04-15 11:20 UTC, ekigamba approved these changes

2021-04-15 11:21 UTC, merged