Add location reposiroty tests
opensrp/opensrp-client-core pull request #824
Opened 2021-08-17 07:48 UTC by Rkareko

2022-03-29 07:55 UTC, bennsimon requested changes

2022-03-29 07:55 UTC, bennsimon commented on opensrp-app/src/test/java/org/smartregister/repository/LocationRepositoryTest.java
> +    public void testMarkLocationsAsSynced(){
KIndly update the test name to match convention test[MethodName][ExpectedResult][Parameters] (Parameters optional if not present).

2022-04-05 07:22 UTC, allan-on commented
@Rkareko Please resolve the merge conflicts indicated

2022-04-05 08:36 UTC, ndegwamartin approved these changes

2022-04-05 08:39 UTC, merged

2022-04-05 08:42 UTC, allan-on approved these changes